---
- name: Download node exporter
  get_url:
    url: https://github.com/prometheus/node_exporter/releases/download/v1.0.1/node_exporter-1.0.1.linux-amd64.tar.gz
    dest: /tmp/node_exporter.tar.gz

- name: Extract node exporter
  unarchive:
    src: /tmp/node_exporter.tar.gz
    dest: /tmp
    remote_src: yes

- name: Move extracted folder
  command: mv /tmp/node_exporter-1.0.1.linux-amd64 /opt/node_exporter

- name: Copy service file
  template:
    src: "node_exporter.service"
    dest: "/etc/systemd/system/node_exporter.service"
    owner: root
    group: root
    mode: 0644

- name: Ensure service auto-starts
  service:
    name: node_exporter
    enabled: yes

- name: Restart service
  service:
    name: node_exporter
    state: restarted

- name: Ensure service is running
  service:
    name: node_exporter
    state: started
    enabled: yes
