---
- name: Update apt cache and install dependencies
  apt:
    name: ["apt-transport-https", "software-properties-common" ]
    state: present

- name: Import Grafana GPG signing key
  apt_key:
    url: "https://packages.grafana.com/gpg.key"
    state: present

- name: Add Grafana repository
  apt_repository:
    repo: "deb https://packages.grafana.com/oss/deb stable main"
    state: present

- name: Install grafana
  apt:
    name: "grafana"
    state: present
    update_cache: yes

- name: Copy default datasource provision
  template:
    src: "default_datasource.yaml"
    dest: "/etc/grafana/provisioning/datasources/default.yaml"
    owner: root
    group: root

- name: Copy default dashboard provision
  template:
    src: "default_dashboard.yaml"
    dest: "/etc/grafana/provisioning/dashboards/default.yaml"
    owner: root
    group: root

- name: Create dashboards directory
  file:
    path: /var/lib/grafana/dashboards
    state: directory
    mode: '0755'

- name: Copy default dashboard json
  template:
    src: "kafka_dashboard.json"
    dest: "/var/lib/grafana/dashboards/kafka.json"
    owner: root
    group: root
    
- name: Start grafana server
  service:
    name: grafana-server
    enabled: yes

- name: Restart service
  service:
    name: grafana-server
    state: restarted

- name: Ensure service is running
  service:
    name: grafana-server
    state: started
    enabled: yes

