---
- name: Download Java OpenJDK 11
  get_url:
    url: "https://download.java.net/java/GA/jdk11/9/GPL/openjdk-11.0.2_linux-x64_bin.tar.gz"
    dest: "/opt/java.tar.gz"

- name: Extract jdk
  unarchive:
    src: /opt/java.tar.gz
    dest: /opt
    remote_src: yes

- name: Move extracted folder to /usr/local
  command: mv /opt/jdk-11.0.2 /usr/local/
  args:
    removes: "/opt/jdk-11.0.2"
    creates: "/usr/local/jdk-11.0.2"

- name: Set bashrc path variable
  command: echo "export JAVA_HOME=/usr/local/jdk-11.0.2" >> /etc/bash.bashrc

- name: Download Kafka
  get_url:
    url: "https://downloads.apache.org/kafka/2.6.0/kafka_2.13-2.6.0.tgz"
    dest: "/opt/kafka.tgz"

- name: Create kafka group
  group:
    name: kafka
    state: present

- name: Create kafka user
  user:
    name: kafka
    groups: kafka
    state: present

- name: Unarchive tgz file
  unarchive:
    src: /opt/kafka.tgz
    dest: /opt
    remote_src: yes

- name: Clean installation folder
  file:
    state: absent
    path: "/etc/kafka"

- name: Move files to system folder
  command: mv /opt/kafka_2.13-2.6.0/ /etc/kafka
  args:
    removes: "/opt/kafka_2.13-2.6.0/"
    creates: "/etc/kafka"

- name: Create directories, set owner, permissions
  file:
    path: "{{ item }}"
    state: "directory"
    owner: kafka
    group: kafka
    mode: 0755
    recurse: yes
  with_items:
    - "etc/kafka"
    - "etc/kafka/data"
    - "/etc/kafka/logs"

- name: Copy systemd service script
  template:
    src: "kafka.service"
    dest: "/etc/systemd/system/kafka.service"
    owner: root
    group: root
    mode: 0644

- name: Ensure service auto-starts
  service:
    name: kafka
    enabled: yes

- name: Restart service
  service:
    name: "kafka"
    state: restarted

- name: Ensure service is running
  service:
    name: kafka
    state: started
    enabled: yes
